### ISSUE TITLE
'account.move.line' nu are metoda cancel

### ISSUE THREAD

**Issue by dhongu** [feketemihai/l10n-romania#100]
In modulul l10n_ro_stock_account in fisier stock_account.py la linia 217 se apleaza metoda cancel care nu exista.

https://github.com/odoo-romania/l10n-romania/blob/8.0/l10n_ro_stock_account/stock_account.py#L217

**Comment by feketemihai** [comment]
Da...greseala mea...clasa e account.move....

**Comment by dhongu** [comment]
Clasa account.move are metoda  button_cancel, poate ca asta trebuie apelata
