### ISSUE TITLE
Plata factura furnizor extern in euro - lei

### ISSUE THREAD

**Issue by bdobrica32** [feketemihai/l10n-romania#115]
Ex: am o factura furnizor 10 euro si cand vreau sa fac payment imi apare default de platit 10 lei. Cum pot sa setez un buton de change currency si sa imi transforme in lei la cursul curent?

**Comment by bdobrica32** [comment]
![1](https://cloud.githubusercontent.com/assets/10671262/11560048/48175036-99c6-11e5-8438-53d5074f018d.png)
![2](https://cloud.githubusercontent.com/assets/10671262/11560047/4813c66e-99c6-11e5-84b4-a52d35d12c42.png)

**Comment by feketemihai** [comment]
Se configureaza un jurnal cu moneda in eur de tip cash...iar la metoda plata se selecteaza jurnalul creeat.

**Comment by bdobrica32** [comment]
Multumesc, Mihai! Setez si revin cu feedback

**Comment by bdobrica32** [comment]
superr! merge! Multumesc!
