### ISSUE TITLE
La print pdf apare eroarea: Wkhtmltopdf failed (error code: -6). 

### ISSUE THREAD

**Issue by bdobrica32** [feketemihai/l10n-romania#116]
Daca insist pana la urma printeaza. Mai apare si cand schimb statusul unei comenzi de achizitii din draft in sent catre supplier

Wkhtmltopdf failed (error code: -6). Message: terminate called after throwing an instance of 'std::bad_alloc'
what(): std::bad_alloc

**Comment by feketemihai** [comment]
De obicei asta vine ori din instalarea lui wkhtmltopdf, sau din configurare unor parametrii.

Vezi:
https://www.odoo.com/forum/help-1/question/wkhtmltopdf-on-v8-not-found-48208

**Comment by bdobrica32** [comment]
rezolvat, ceva la parametrii de pe server. 

Multumesc!
