### ISSUE TITLE
Mesaj de eroare: "Unable to install module "l10n_ro_hr" because an external dependency is not met: No module named stdnum"

### ISSUE THREAD

**Issue by sebytza05** [feketemihai/l10n-romania#134]
Buna ziua,
Am incercat sa instalez functionalitatile modulului de Romania pe o baza de date noua si primesc aceasta eroare: ![image](https://cloud.githubusercontent.com/assets/19728451/18905936/177ae458-856e-11e6-964a-3d73190a2cf1.png).
Ma puteti ajuta?
Va multumesc

**Comment by feketemihai** [comment]
Salut, trebuie sa instalezi libraria stdnum cu sudo pip install stdnum, numai sa vezi sa fie peste versiunea 0.9…cea implicita din linux 14 era parca 0.6….

Mihai Fekete
OpenErp Specialist

E-Mail:       mihai.fekete@forbiom.eumailto:mihai.fekete@forbiom.eu
Mobile:      +4(0) 746 – 028 477
Office:       +4(0) 356 – 173 953

Forest and Biomass Services Romania S.A.
Address: 11A Calea Buziasului, building B, 3rd floor | Timisoara 300699 | Romania

**Comment by sebytza05** [comment]
Multumesc, am rezolvat cu instalarea.

**Comment by sebytza05** [comment]
Am intampinat alta eroare la acrivarea functionalitatii Romania Accounting Reports
![image](https://cloud.githubusercontent.com/assets/19728451/18909732/690f2eaa-857d-11e6-96f5-a14918c1bb82.png)

**Comment by feketemihai** [comment]
Ciudat...ca dependinta l10n_ro_config depinde de l10n_ro, care are judetele declarate...incearca sa instalezi prima data Planul de Conturi, modulul l10n_ro din modulele de baza ale Odoo...

**Comment by sebytza05** [comment]
Am instalat Planul de conturi din modulul Accounting and Finance. Am instalat si alte functionalitati ale modulului Romania Accounting si nu am avut probleme. Singurele functionalitati care imi dau eroare sunt Romania Accounting Reports si Romania Cities banuiesc ca Accounting Reports are dependenta de Cities, dar nu inteleg de ce imi da eroare la Romania Cities. Aceasta este eroarea de la Romania Cities: 
![image](https://cloud.githubusercontent.com/assets/19728451/18911117/cf09c26e-8583-11e6-87ca-3ed7d64b8f07.png)

**Comment by feketemihai** [comment]
Dupa eroare...vede ca l10n_ro.RO_AB nu este in baza de date, si incearca sa creeze unul nou, dar e definit in l10n_ro...https://github.com/odoo/odoo/blob/8.0/addons/l10n_ro/res.country.state.csv de asta mi se pare ciudat...

**Comment by sebytza05** [comment]
Nici nu aveam acele csv-uri in l10n_ro , le-am luat de pe github si le-am copiat in folderul meu, dar acum am alata eroare :(

Exception: Module loading l10n_ro_account_report failed: file l10n_ro_account_report/security/ir.model.access.csv could not be processed:
 Line 1 : No matching record found for external id 'model_report_394_code' in field 'Object'

**Comment by feketemihai** [comment]
Salut, am facut un commit prin care am mutat vechea D394 in noul modul pentru ea, si actualizare lista module in meniul de config si readme. Fa-ti un pull nou si update....

**Comment by sebytza05** [comment]
Salutare Mihai,

Am actualizat, chiar am facut si o baza de date noua si din pacate imi da alta eroare la instalarea modului de Romania :(

Error details:
Field `module_l10n_ro_account_report_d394` does not exist

Error context:
View `Romania Settings`
[view_id: 560, xml_id: n/a, model: l10n.ro.config.settings, parent_id: n/a]" while parsing /opt/bitnami/apps/odoo/lib/odoo-8.0_a2115ef-py2.7.egg/openerp/addons/l10n_ro_config/res_config_view.xml:5, near
<record id="view_l10n_ro_config_settings" model="ir.ui.view">
            <field name="name">Romania Settings</field>
            <field name="model">l10n.ro.config.settings</field>
            <field name="arch" type="xml">
                <form string="Configure Romania Application" class="oe_form_configuration">
                    <header>
                        <button string="Apply" type="object" name="execute" class="oe_highlight"/>
                        or
                        <button string="Cancel" type="object" name="cancel" class="oe_link"/>
                    </header>
                    <group groups="base.group_multi_company">
                        <div>
                            <field name="has_default_company" invisible="1"/>
                            <div attrs="{'invisible': [('has_default_company', '=', True)]}">
                                <label for="company_id" string="Select Company"/>
                                <field name="company_id" widget="selection" on_change="onchange_company_id(company_id)" class="oe_inline"/>
                            </div>
                        </div>
                    </group>
                    <group string="Partner and Address Book">
                        <label for="id" string="Partners"/>
                        <div>
                            <div>
                                <field name="module_partner_create_by_vat" class="oe_inline"/>
                                <label for="module_partner_create_by_vat"/>
                            </div>
                            <div>
                                <field name="module_l10n_ro_fiscal_validation" class="oe_inline"/>
                                <label for="module_l10n_ro_fiscal_validation"/>
                            </div>
                            <div>
                                <field name="module_l10n_ro_partner_unique" class="oe_inline"/>
                                <label for="module_l10n_ro_partner_unique"/>
                            </div>
                            <div>
                                <field name="module_l10n_ro_contact_address" class="oe_inline"/>
                                <label for="module_l10n_ro_contact_address"/>
                            </div>
                        </div>
                        <label for="id" string="Address Book"/>
                        <div>
                            <div>
                                <field name="module_l10n_ro_siruta" class="oe_inline"/>
                                <label for="module_l10n_ro_siruta"/>
                                <group attrs="{'invisible': [('module_l10n_ro_siruta', '&lt;&gt;', True)]}" col="2">
                                    <group>
                                        <field name="siruta_update"/>
                                    </group>
                                    <group>
                                    </group>
                                </group>
                            </div>
                        </div>
                    </group>
                    <group string="Accounting">
                        <label for="id" string="General Features"/>
                        <div>
                            <div>
                                <field name="module_account_storno" class="oe_inline"/>
                                <label for="module_account_storno"/>
                            </div>
                            <div>
                                <field name="module_account_vat_on_payment" class="oe_inline"/>
                                <label for="module_account_vat_on_payment"/>
                            </div>
                            <div>
                                <field name="module_account_compensation" class="oe_inline"/>
                                <label for="module_account_compensation"/>
                            </div>
                            <div>
                                <field name="module_account_compensation_vat_on_payment" class="oe_inline"/>
                                <label for="module_account_compensation_vat_on_payment"/>
                            </div>
                        </div>
                        <label for="id" string="Romania Adaptation"/>
                        <div>
                            <div>
                                <group col="2">
                                    <group>
                                        <field name="property_customer_advance_account_id"/>
                                        <field name="property_supplier_advance_account_id"/>
                                    </group>
                                    <group>
                                    </group>
                                </group>
                            </div>
                            <div>
                                <field name="module_l10n_ro_account_constrains" class="oe_inline"/>
                                <label for="module_l10n_ro_account_constrains"/>
                            </div>
                            <div>
                                <field name="module_l10n_ro_invoice_line_not_deductible" class="oe_inline"/>
                                <label for="module_l10n_ro_invoice_line_not_deductible"/>
                                <group attrs="{'invisible': [('module_l10n_ro_invoice_line_not_deductible', '&lt;&gt;', True)]}" col="2">
                                    <group>
                                        <field name="property_undeductible_account_id"/>
                                        <field name="property_undeductible_tax_account_id"/>
                                    </group>
                                    <group>
                                    </group>
                                </group>
                            </div>
                            <div>
                                <field name="module_l10n_ro_account_bank_statement" class="oe_inline"/>
                                <label for="module_l10n_ro_account_bank_statement"/>
                                <group attrs="{'invisible': [('module_l10n_ro_account_bank_statement', '&lt;&gt;', True)]}" col="2">
                                    <group>
                                        <field name="bank_statement_template_installed"/>
                                    </group>
                                    <group>
                                    </group>
                                </group>
                            </div>
                            <div>
                                <field name="module_l10n_ro_account_bank_statement_import_mt940_brd" class="oe_inline"/>
                                <label for="module_l10n_ro_account_bank_statement_import_mt940_brd"/>
                            </div>
                            <div>
                                <field name="module_l10n_ro_account_voucher_cash" class="oe_inline"/>
                                <label for="module_l10n_ro_account_voucher_cash"/>
                            </div>
                            <div>
                                <field name="module_l10n_ro_asset" class="oe_inline"/>
                                <label for="module_l10n_ro_asset"/>
                                <group attrs="{'invisible': [('module_l10n_ro_asset', '&lt;&gt;', True)]}" col="2">
                                    <group>
                                        <field name="property_asset_reevaluation_account_id"/>
                                        <field name="asset_category_chart_installed"/>
                                    </group>
                                    <group>
                                    </group>
                                </group>
                            </div>
                            <div>
                                <field name="module_l10n_ro_account_voucher_currency_update" class="oe_inline"/>
                                <label for="module_l10n_ro_account_voucher_currency_update"/>
                            </div>
                            <div>
                                <field name="module_l10n_ro_account_compensation_currency_update" class="oe_inline"/>
                                <label for="module_l10n_ro_account_compensation_currency_update"/>
                            </div>
                        </div>
                        <label for="id" string="Period Closing"/>
                        <div>
                            <div>
                                <field name="module_l10n_ro_currency_reevaluation" class="oe_inline"/>
                                <label for="module_l10n_ro_currency_reevaluation"/>
                            </div>
                            <div>
                                <field name="module_l10n_ro_account_period_close" class="oe_inline"/>
                                <label for="module_l10n_ro_account_period_close"/>
                                <group attrs="{'invisible': [('module_l10n_ro_account_period_close', '&lt;&gt;', True)]}" col="2">
                                    <group>
                                        <field name="account_period_close_template_installed"/>
                                    </group>
                                    <group>
                                    </group>
                                </group>
                            </div>
                        </div>
                        <label for="id" string="Reporting"/>
                        <div>
                            <div>
                                <field name="module_l10n_ro_invoice_report" class="oe_inline"/>
                                <label for="module_l10n_ro_invoice_report"/>
                            </div>
                            <div>
                                <field name="module_l10n_ro_account_report" class="oe_inline"/>
                                <label for="module_l10n_ro_account_report"/>
                            </div>
                            <div>
                                <field name="module_l10n_ro_account_report_d394" class="oe_inline"/>
                                <label for="module_l10n_ro_account_report_d394"/>
                            </div>
                        </div>
                    </group>
                    <group string="Stock">
                        <label for="id" string="Stock &amp; Stock Accounting"/>
                        <div>
                            <div>
                                <field name="module_l10n_ro_stock" class="oe_inline"/>
                                <label for="module_l10n_ro_stock"/>
                            </div>
                            <div>
                                <field name="module_l10n_ro_stock_account" class="oe_inline"/>
                                <label for="module_l10n_ro_stock_account"/>
                                <group attrs="{'invisible': [('module_l10n_ro_stock_account', '&lt;&gt;', True)]}" col="2">
                                    <group>
                                        <field name="property_stock_picking_receivable_account_id"/>
                                        <field name="property_stock_picking_payable_account_id"/>
                                        <field name="property_stock_usage_giving_account_id"/>
                                        <field name="property_stock_picking_custody_account_id"/>
                                    </group>
                                    <group>
                                    </group>
                                </group>
                            </div>
                            <div>
                                <field name="module_l10n_ro_stock_picking_report" class="oe_inline"/>
                                <label for="module_l10n_ro_stock_picking_report"/>
                            </div>
                        </div>
                    </group>
                    <group string="General">
                        <label for="id" string="Currency Update"/>
                        <div>
                            <div>
                                <field name="module_currency_rate_update" class="oe_inline"/>
                                <label for="module_currency_rate_update"/>
                            </div>
                        </div>
                    </group>
                </form>
            </field>
        </record>

**Comment by feketemihai** [comment]
Salut...campul a fost adaugat in commitul de azi dimineata si am testat si creearea unei bd noi...ceva iti scapa ori la pull ori la updateul serverului...

**Comment by feketemihai** [comment]
Da-mi un RDP sau team viewer sa vad si eu care e de fapt problema...

**Comment by sebytza05** [comment]
Am reusit pana la urma dupa un update de server, acum da eroare la crearea unei facturi de clienti:

/openerp/addons/l10n_ro_account_report_d394/models/account_invoice.py", line 55, in _get_inv_number
    inv_seq.with_context(ctx)._interpolation_dict_context())
AttributeError: 'ir.sequence' object has no attribute '_interpolation_dict_context'

Ti-am trimis un e-mail cu detaliile de conectare de la Team Viewer, doar in cazul in care nu ai treaba.

Mersi fain

**Comment by feketemihai** [comment]
Wrong Odoo version....
