### ISSUE TITLE
currency rate update

### ISSUE THREAD

**Issue by yoyo2k** [feketemihai/l10n-romania#47]
mie nu-mi functioneaza update-ul de curs valutar decat daca apas butonul din configuratia companiei.

Se mai intampla cuiva?

**Comment by feketemihai** [comment]
Trebuie sa iti completezi next_run on cu urmatoarea zi, adica 31.01.2015, si atunci cron-ul vede ca acel serviciu trebuie actualizat in ziua respective…si proceseaza si urmatoarea rulare…

Mihai Fekete
OpenErp Specialist

E-Mail:       mihai.fekete@forbiom.eumailto:mihai.fekete@forbiom.eu
Mobile:      +4(0) 746 – 028 477
Office:       +4(0) 356 – 173 953

Forest and Biomass Services Romania S.A.
Address: 10 Coriolan Brediceanu | City Business Centre | Timisoara 300011 | Romania

**Comment by feketemihai** [comment]
Poti sa iti pui si acuma pe 30.01.2015 next_run, si sa modifici cron-ul ca sa vezi daca merge...

**Comment by yoyo2k** [comment]
next run de la cron? sau din configurarea companiei?
in configurarea companiei am pus.. si ramane setata asa..

**Comment by feketemihai** [comment]
Nu..next run la serviciu de actualizare monede …sigur iti e ramas in urma…

Mihai Fekete
OpenErp Specialist

E-Mail:       mihai.fekete@forbiom.eumailto:mihai.fekete@forbiom.eu
Mobile:      +4(0) 746 – 028 477
Office:       +4(0) 356 – 173 953

Forest and Biomass Services Romania S.A.
Address: 10 Coriolan Brediceanu | City Business Centre | Timisoara 300011 | Romania

**Comment by yoyo2k** [comment]
pai nu trebuie sa se actualizeze automat?

Next Execution Date: 01/30/2015 16:27:45

**Comment by feketemihai** [comment]
Se actualizeaza daca iti pui prima rulare…

Mihai Fekete
OpenErp Specialist

E-Mail:       mihai.fekete@forbiom.eumailto:mihai.fekete@forbiom.eu
Mobile:      +4(0) 746 – 028 477
Office:       +4(0) 356 – 173 953

Forest and Biomass Services Romania S.A.
Address: 10 Coriolan Brediceanu | City Business Centre | Timisoara 300011 | Romania

**Comment by yoyo2k** [comment]
ok
