### ISSUE TITLE
l10n_ro_hr casang

### ISSUE THREAD

**Issue by yoyo2k** [feketemihai/l10n-romania#48]
la instalare ridica exceptia ca nu poate seta coloana casang not null pt ca nu are un default.
la instalare iti face adminu angajat...
merge pus default='_B' ?

**Comment by feketemihai** [comment]
Nu merge ca angajatul e deja creeat…default se refera la cei ce ii creezi dupa aceea…si daca pui data sa faca cel putin admin-ul tot nu e relevant…

Mihai Fekete
OpenErp Specialist

E-Mail:       mihai.fekete@forbiom.eumailto:mihai.fekete@forbiom.eu
Mobile:      +4(0) 746 – 028 477
Office:       +4(0) 356 – 173 953

Forest and Biomass Services Romania S.A.
Address: 10 Coriolan Brediceanu | City Business Centre | Timisoara 300011 | Romania

**Comment by yoyo2k** [comment]
ok.. mai e o singura problema atunci la hr.. face round la coef de risc ex. in loc de 0.214 imi apare in bd 0.21.

s-ar rezolva cu digits=(0,4)?

**Comment by feketemihai** [comment]
Da…

Mihai Fekete
OpenErp Specialist

E-Mail:       mihai.fekete@forbiom.eumailto:mihai.fekete@forbiom.eu
Mobile:      +4(0) 746 – 028 477
Office:       +4(0) 356 – 173 953

Forest and Biomass Services Romania S.A.
Address: 10 Coriolan Brediceanu | City Business Centre | Timisoara 300011 | Romania

**Comment by yoyo2k** [comment]
merge?
