### ISSUE TITLE
problema coduri tva

### ISSUE THREAD

**Issue by yoyo2k** [feketemihai/l10n-romania#55]
Daca se foloseste l10n_ro din gh:odoo-romania/odoo unde este la zi si nu cel din gh:odoo/odoo, Mihai a adus la zi partea de taxe... ce facem cu folosirea codurilor vechi?
de ex: in account_vat_on_payment/vat_on_payment.xml 

probabil mai sunt si altele dar asta mi-a sarit in ochi

**Comment by feketemihai** [comment]
Fisierul trebuie sters de acolo..oricum nu il mai incarca...taxele pt tva la incasare se configureaza automat in l10n_ro_config la instalare vat_on_payment...

**Comment by yoyo2k** [comment]
ok
