### ISSUE TITLE
l10n_ro_hr/hr_employee.py", line 25   are o dependinta lipsa 

### ISSUE THREAD

**Issue by cbssolutions** [feketemihai/l10n-romania#59]
File "/opt/odoo8/l10n-romania/l10n_ro_hr/hr_employee.py", line 25, in <module>
    from stdnum.ro.cnp import get_birth_date, is_valid as validate_cnp
ImportError: No module named stdnum.ro.cnp

**Comment by yoyo2k** [comment]
normal ar trebui sa fie instalat din dependinte..
base_vat -> vatnumber -> stdnum
https://github.com/odoo/odoo/blob/8.0/addons/base_vat/base_vat.py
https://code.google.com/p/vatnumber/source/browse/setup.py

**Comment by yoyo2k** [comment]
if all else fails:
pip install stdnum

**Comment by cbssolutions** [comment]
merge cu instalarea stdnum
