### ISSUE TITLE
eroare la instalare in   ln10n_ro_config 

### ISSUE THREAD

**Issue by cbssolutions** [feketemihai/l10n-romania#60]
File "/opt/odoo8/l10n-romania/l10n_ro_config/res_config.py", line 234, in execute
    if not tax.not_deductible_tax_id:
AttributeError: 'account.tax' object has no attribute 'not_deductible_tax_id'

**Comment by feketemihai** [comment]
Trebuie reglata…daca ami dai o data apply merge…

Mihai Fekete
OpenErp Specialist

E-Mail:       mihai.fekete@forbiom.eumailto:mihai.fekete@forbiom.eu
Mobile:      +4(0) 746 – 028 477
Office:       +4(0) 356 – 173 953

Forest and Biomass Services Romania S.A.
Address: 10 Coriolan Brediceanu | City Business Centre | Timisoara 300011 | Romania
