### ISSUE TITLE
!!! Odoo Community Project !!!

### ISSUE THREAD

**Issue by feketemihai** [feketemihai/l10n-romania#70]
As vrea parerea voastra cu privire la mutarea proiectului in Odoo Community, odata mutat tot cei ce contribuie si fac parte din echipa de localizare trebuie sa semneze CLA (plus subscription 50 EUR pe an)???

Mutarea se va face in timp, modul cu modul, odata cu code review, teste adaugate...compliance cu OCA...

**Comment by cbssolutions** [comment]
Ok din partea mea.

**Comment by yoyo2k** [comment]
Şi eu sunt de acord. Dar cine te pune să semnezi? Că am un pr pe hr_webcam de 2 săptămâni şi astept să dea merge să le dau şi hr_payroll_extensions cu toate dependențele.

**Comment by feketemihai** [comment]
Ca sa contribui la codul din OCA va trebui sa semnezi CLA-ul...pana acum nu toti cei care contribuie aveau semnat...dar in viitor o sa fie obligatoriu sa ai semnat ca sa se aprobe pr-ul...de hr_webcam am vazut ca ai..trebuie sa mai dai un reply sa vezi cine e responsabil de proiect-ul pe hr...

**Comment by yoyo2k** [comment]
Niste intrebari/nedumeriri:
1. Relicenţierea: (f importantă)
Odoo trece la lgpl, oca rămâne pe agpl până când? Cla în viitor, când code base-ul va fi doar din commit-uri de la utilizatori care au semnat cla, vor putea să schimbe licenţa.
1. Trebuie să fie cel puţin 2 membri care să plătească taxa anuală pt a avea proiectul în oca (revieweri)
2. Oca oferă ci + o bază mai mare de dev. Câti? 3?

**Comment by crixus10** [comment]
si eu sunt ok.

**Comment by mcojocaru** [comment]
si eu sunt ok.

**Comment by feketemihai** [comment]
In OCA nu cred ca o sa fie module care se vor plati, si dupa comunicatul lor va fi greu de trecut de la AGPL in LGPL: http://odoo-community.org/blog/news-1/post/odoo-relicensing-11, o sa vorbesc saptamana viitoare care sunt conditiile ca proiectul sa fie postat...

**Comment by feketemihai** [comment]
The project for Romania has been created under OCA

https://github.com/OCA/l10n-romania

The project will be moved slowly on the OCA github account.

OCA/l10n-romania github.com
l10n-romania - Romanian Localization for Odoo
