### ISSUE TITLE
New Chart of Accounts according to 1st of January - Master Branch

### ISSUE THREAD

**Issue by feketemihai** [feketemihai/l10n-romania#88]
Noul plan de conturi si taxe revizuit pentru master:

https://github.com/feketemihai/odoo/tree/master-account-new-api-mdi-l10n_ro-cod

Puteti testa si voi daca aveti timp???

**Comment by sharkutz** [comment]
What would you like to be tested? if Class 8 and 9 are functional?

**Comment by feketemihai** [comment]
It's more about new account types...which are done based on the balance sheet, taxes with the new system...

**Comment by sharkutz** [comment]
TCD document? something to start with?

**Comment by feketemihai** [comment]
Not yet...it's more about accounting functionality and reports
